//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grbl.Master.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mssages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mssages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("grbl.Master.Model.Resources.Mssages", typeof(Mssages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard limit triggered. Machine position is likely lost due to sudden and immediate halt. Re-homing is highly recommended..
        /// </summary>
        public static string Alarm_1 {
            get {
                return ResourceManager.GetString("Alarm:1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code motion target exceeds machine travel. Machine position safely retained. Alarm may be unlocked..
        /// </summary>
        public static string Alarm_2 {
            get {
                return ResourceManager.GetString("Alarm:2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset while in motion. Grbl cannot guarantee position. Lost steps are likely. Re-homing is highly recommended..
        /// </summary>
        public static string Alarm_3 {
            get {
                return ResourceManager.GetString("Alarm:3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe fail. The probe is not in the expected initial state before starting probe cycle, where G38.2 and G38.3 is not triggered and G38.4 and G38.5 is triggered..
        /// </summary>
        public static string Alarm_4 {
            get {
                return ResourceManager.GetString("Alarm:4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe fail. Probe did not contact the workpiece within the programmed travel for G38.2 and G38.4..
        /// </summary>
        public static string Alarm_5 {
            get {
                return ResourceManager.GetString("Alarm:5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Reset during active homing cycle..
        /// </summary>
        public static string Alarm_6 {
            get {
                return ResourceManager.GetString("Alarm:6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Safety door was opened during active homing cycle..
        /// </summary>
        public static string Alarm_7 {
            get {
                return ResourceManager.GetString("Alarm:7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Cycle failed to clear limit switch when pulling off. Try increasing pull-off setting or check wiring..
        /// </summary>
        public static string Alarm_8 {
            get {
                return ResourceManager.GetString("Alarm:8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing fail. Could not find limit switch within search distance. Defined as 1.5 * max_travel on search and 5 * pulloff on locate phases..
        /// </summary>
        public static string Alarm_9 {
            get {
                return ResourceManager.GetString("Alarm:9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door closed. Ready to resume..
        /// </summary>
        public static string Door_0 {
            get {
                return ResourceManager.GetString("Door:0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine stopped. Door still ajar. Can&apos;t resume until closed..
        /// </summary>
        public static string Door_1 {
            get {
                return ResourceManager.GetString("Door:1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door opened. Hold (or parking retract) in-progress. Reset will throw an alarm..
        /// </summary>
        public static string Door_2 {
            get {
                return ResourceManager.GetString("Door:2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door closed and resuming. Restoring from park, if applicable. Reset will throw an alarm..
        /// </summary>
        public static string Door_3 {
            get {
                return ResourceManager.GetString("Door:3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code words consist of a letter and a value. Letter was not found..
        /// </summary>
        public static string error_1 {
            get {
                return ResourceManager.GetString("error:1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft limits cannot be enabled without homing also enabled..
        /// </summary>
        public static string error_10 {
            get {
                return ResourceManager.GetString("error:10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max characters per line exceeded. Line was not processed and executed..
        /// </summary>
        public static string error_11 {
            get {
                return ResourceManager.GetString("error:11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Compile Option) Grbl &apos;$&apos; setting value exceeds the maximum step rate supported..
        /// </summary>
        public static string error_12 {
            get {
                return ResourceManager.GetString("error:12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety door detected as opened and door state initiated..
        /// </summary>
        public static string error_13 {
            get {
                return ResourceManager.GetString("error:13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Grbl-Mega Only) Build info or startup line exceeded EEPROM line length limit..
        /// </summary>
        public static string error_14 {
            get {
                return ResourceManager.GetString("error:14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog target exceeds machine travel. Command ignored..
        /// </summary>
        public static string error_15 {
            get {
                return ResourceManager.GetString("error:15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog command with no &apos;=&apos; or contains prohibited g-code..
        /// </summary>
        public static string error_16 {
            get {
                return ResourceManager.GetString("error:16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser mode requires PWM output..
        /// </summary>
        public static string error_17 {
            get {
                return ResourceManager.GetString("error:17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value format is not valid or missing an expected value..
        /// </summary>
        public static string error_2 {
            get {
                return ResourceManager.GetString("error:2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported or invalid g-code command found in block..
        /// </summary>
        public static string error_20 {
            get {
                return ResourceManager.GetString("error:20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one g-code command from same modal group found in block..
        /// </summary>
        public static string error_21 {
            get {
                return ResourceManager.GetString("error:21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed rate has not yet been set or is undefined..
        /// </summary>
        public static string error_22 {
            get {
                return ResourceManager.GetString("error:22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code command in block requires an integer value..
        /// </summary>
        public static string error_23 {
            get {
                return ResourceManager.GetString("error:23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two G-code commands that both require the use of the XYZ axis words were detected in the block..
        /// </summary>
        public static string error_24 {
            get {
                return ResourceManager.GetString("error:24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G-code word was repeated in the block..
        /// </summary>
        public static string error_25 {
            get {
                return ResourceManager.GetString("error:25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G-code command implicitly or explicitly requires XYZ axis words in the block, but none were detected..
        /// </summary>
        public static string error_26 {
            get {
                return ResourceManager.GetString("error:26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N line number value is not within the valid range of 1 - 9,999,999..
        /// </summary>
        public static string error_27 {
            get {
                return ResourceManager.GetString("error:27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G-code command was sent, but is missing some required P or L value words in the line..
        /// </summary>
        public static string error_28 {
            get {
                return ResourceManager.GetString("error:28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl supports six work coordinate systems G54-G59. G59.1, G59.2, and G59.3 are not supported..
        /// </summary>
        public static string error_29 {
            get {
                return ResourceManager.GetString("error:29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl &apos;$&apos; system command was not recognized or supported..
        /// </summary>
        public static string error_3 {
            get {
                return ResourceManager.GetString("error:3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The G53 G-code command requires either a G0 seek or G1 feed motion mode to be active. A different motion was active..
        /// </summary>
        public static string error_30 {
            get {
                return ResourceManager.GetString("error:30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unused axis words in the block and G80 motion mode cancel is active..
        /// </summary>
        public static string error_31 {
            get {
                return ResourceManager.GetString("error:31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G2 or G3 arc was commanded but there are no XYZ axis words in the selected plane to trace the arc..
        /// </summary>
        public static string error_32 {
            get {
                return ResourceManager.GetString("error:32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motion command has an invalid target. G2, G3, and G38.2 generates this error, if the arc is impossible to generate or if the probe target is the current position..
        /// </summary>
        public static string error_33 {
            get {
                return ResourceManager.GetString("error:33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G2 or G3 arc, traced with the radius definition, had a mathematical error when computing the arc geometry. Try either breaking up the arc into semi-circles or quadrants, or redefine them with the arc offset definition..
        /// </summary>
        public static string error_34 {
            get {
                return ResourceManager.GetString("error:34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G2 or G3 arc, traced with the offset definition, is missing the IJK offset word in the selected plane to trace the arc..
        /// </summary>
        public static string error_35 {
            get {
                return ResourceManager.GetString("error:35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unused, leftover G-code words that aren&apos;t used by any command in the block..
        /// </summary>
        public static string error_36 {
            get {
                return ResourceManager.GetString("error:36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The G43.1 dynamic tool length offset command cannot apply an offset to an axis other than its configured axis. The Grbl default axis is the Z-axis..
        /// </summary>
        public static string error_37 {
            get {
                return ResourceManager.GetString("error:37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool number greater than max supported value..
        /// </summary>
        public static string error_38 {
            get {
                return ResourceManager.GetString("error:38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative value received for an expected positive value..
        /// </summary>
        public static string error_4 {
            get {
                return ResourceManager.GetString("error:4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing cycle is not enabled via settings..
        /// </summary>
        public static string error_5 {
            get {
                return ResourceManager.GetString("error:5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum step pulse time must be greater than 3ms (millisecond).
        /// </summary>
        public static string error_6 {
            get {
                return ResourceManager.GetString("error:6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM read failed. Reset and restored to default values..
        /// </summary>
        public static string error_7 {
            get {
                return ResourceManager.GetString("error:7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grbl &apos;$&apos; command cannot be used unless Grbl is IDLE. Ensures smooth operation during a job..
        /// </summary>
        public static string error_8 {
            get {
                return ResourceManager.GetString("error:8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code locked out during alarm or jog state.
        /// </summary>
        public static string error_9 {
            get {
                return ResourceManager.GetString("error:9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold complete. Ready to resume..
        /// </summary>
        public static string Hold_0 {
            get {
                return ResourceManager.GetString("Hold:0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold in-progress. Reset will throw an alarm..
        /// </summary>
        public static string Hold_1 {
            get {
                return ResourceManager.GetString("Hold:1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step pulse time, microseconds.
        /// </summary>
        public static string Setting_0_Description {
            get {
                return ResourceManager.GetString("Setting:0:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step idle delay, milliseconds.
        /// </summary>
        public static string Setting_1_Description {
            get {
                return ResourceManager.GetString("Setting:1:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status report options, mask.
        /// </summary>
        public static string Setting_10_Description {
            get {
                return ResourceManager.GetString("Setting:10:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis steps per millimeter.
        /// </summary>
        public static string Setting_100_Description {
            get {
                return ResourceManager.GetString("Setting:100:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis steps per millimeter.
        /// </summary>
        public static string Setting_101_Description {
            get {
                return ResourceManager.GetString("Setting:101:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis steps per millimeter.
        /// </summary>
        public static string Setting_102_Description {
            get {
                return ResourceManager.GetString("Setting:102:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction deviation, millimeters.
        /// </summary>
        public static string Setting_11_Description {
            get {
                return ResourceManager.GetString("Setting:11:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis maximum rate, mm/min.
        /// </summary>
        public static string Setting_110_Description {
            get {
                return ResourceManager.GetString("Setting:110:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis maximum rate, mm/min.
        /// </summary>
        public static string Setting_111_Description {
            get {
                return ResourceManager.GetString("Setting:111:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis maximum rate, mm/min.
        /// </summary>
        public static string Setting_112_Description {
            get {
                return ResourceManager.GetString("Setting:112:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc tolerance, millimeters.
        /// </summary>
        public static string Setting_12_Description {
            get {
                return ResourceManager.GetString("Setting:12:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis acceleration, mm/sec^2.
        /// </summary>
        public static string Setting_120_Description {
            get {
                return ResourceManager.GetString("Setting:120:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis acceleration, mm/sec^2.
        /// </summary>
        public static string Setting_121_Description {
            get {
                return ResourceManager.GetString("Setting:121:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis acceleration, mm/sec^2.
        /// </summary>
        public static string Setting_122_Description {
            get {
                return ResourceManager.GetString("Setting:122:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report in inches, boolean.
        /// </summary>
        public static string Setting_13_Description {
            get {
                return ResourceManager.GetString("Setting:13:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis maximum travel, millimeters.
        /// </summary>
        public static string Setting_130_Description {
            get {
                return ResourceManager.GetString("Setting:130:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis maximum travel, millimeters.
        /// </summary>
        public static string Setting_131_Description {
            get {
                return ResourceManager.GetString("Setting:131:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-axis maximum travel, millimeters.
        /// </summary>
        public static string Setting_132_Description {
            get {
                return ResourceManager.GetString("Setting:132:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step pulse invert, mask.
        /// </summary>
        public static string Setting_2_Description {
            get {
                return ResourceManager.GetString("Setting:2:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft limits enable, boolean.
        /// </summary>
        public static string Setting_20_Description {
            get {
                return ResourceManager.GetString("Setting:20:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard limits enable, boolean.
        /// </summary>
        public static string Setting_21_Description {
            get {
                return ResourceManager.GetString("Setting:21:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing cycle enable, boolean.
        /// </summary>
        public static string Setting_22_Description {
            get {
                return ResourceManager.GetString("Setting:22:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing direction invert, mask.
        /// </summary>
        public static string Setting_23_Description {
            get {
                return ResourceManager.GetString("Setting:23:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing locate feed rate, mm/min.
        /// </summary>
        public static string Setting_24_Description {
            get {
                return ResourceManager.GetString("Setting:24:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing search seek rate, mm/min.
        /// </summary>
        public static string Setting_25_Description {
            get {
                return ResourceManager.GetString("Setting:25:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing switch debounce delay, milliseconds.
        /// </summary>
        public static string Setting_26_Description {
            get {
                return ResourceManager.GetString("Setting:26:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing switch pull-off distance, millimeters.
        /// </summary>
        public static string Setting_27_Description {
            get {
                return ResourceManager.GetString("Setting:27:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step direction invert, mask.
        /// </summary>
        public static string Setting_3_Description {
            get {
                return ResourceManager.GetString("Setting:3:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum spindle speed, RPM.
        /// </summary>
        public static string Setting_30_Description {
            get {
                return ResourceManager.GetString("Setting:30:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum spindle speed, RPM.
        /// </summary>
        public static string Setting_31_Description {
            get {
                return ResourceManager.GetString("Setting:31:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser-mode enable, boolean.
        /// </summary>
        public static string Setting_32_Description {
            get {
                return ResourceManager.GetString("Setting:32:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert step enable pin, boolean.
        /// </summary>
        public static string Setting_4_Description {
            get {
                return ResourceManager.GetString("Setting:4:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert limit pins, boolean.
        /// </summary>
        public static string Setting_5_Description {
            get {
                return ResourceManager.GetString("Setting:5:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert probe pin, boolean.
        /// </summary>
        public static string Setting_6_Description {
            get {
                return ResourceManager.GetString("Setting:6:Description", resourceCulture);
            }
        }
    }
}
